branches:
    only:
        - master
        - develop

language: python
python:
    - "3.7"
cache: pip
install:
    - pip install pylint Flask Flask-Cors passlib peewee validate-email
script: pylint backend

