branches:
    only:
        - master
        - develop        

matrix:
    include:
      - language: python
        dist: xenial
        python:
            - "3.7"
        cache: pip
        install:
            - pip install pylint Flask Flask-Cors passlib peewee validate-email doxypypy
        script:
            pylint --errors-only backend;
            python backend/run_tests.py
            
      - language: node_js
        node_js:
            - "8.15.1"
        before_install:
            cd frontend
        install:
            - npm install eslint
        script:
            npm test
            
      - branches:
            only:
                - develop
        language: python
        dist: xenial
        python:
            - "3.7"
        cache: pip
        install:
            - pip install doxypypy
        addons:
            apt:
              packages:
                - doxygen
        before_script:
            cd backend
        script:
            - doxygen Doxyfile
        deploy:
          provider: pages
          skip_cleanup: true
          local_dir: docs/html
          github_token: $GH_REPO_TOKEN
          on:
            branch: develop

